CandidateProject/ViewModels/AddEquipmentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CandidateProject.ViewModels
{
    public class AddEquipmentViewModel
    {
        public int CartonId { get; set; }
        public int EquipmentId { get; set; }
    }
}

CandidateProject/ViewModels/CartonViewModel.cs
namespace CandidateProject.ViewModels
{
    public class CartonViewModel
    {
        public int Id { get; set; }
        public string CartonNumber { get; set; }
        public int EquipmentCount { get; set; } //enhancement1
    }
}

CandidateProject/Controllers/CartonController.cs
using CandidateProject.EntityModels;
using CandidateProject.ViewModels;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace CandidateProject.Controllers
{
    public class CartonController : Controller
    {
        private CartonContext db = new CartonContext();

        // GET: Carton
        // public ActionResult Index()
        // {
        //     var cartons = db.Cartons
        //         .Select(c => new CartonViewModel()
        //         {
        //             Id = c.Id,
        //             CartonNumber = c.CartonNumber
        //         })
        //         .ToList();

        //     return View(cartons);
        // }
        //ENhancement1
        public ActionResult Index()
        {
            var cartons = db.Cartons
                .Include(c => c.CartonDetails)
                .Select(c => new
                {
                    Carton = c,
                    EquipmentCount = c.CartonDetails.Count
                })
                .ToList();

            return View(cartons);
        }

        // GET: Carton/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var carton = db.Cartons
                .Where(c => c.Id == id)
                .Select(c => new CartonViewModel()
                {
                    Id = c.Id,
                    CartonNumber = c.CartonNumber
                })
                .SingleOrDefault();
            if (carton == null)
            {
                return HttpNotFound();
            }
            return View(carton);
        }

        // GET: Carton/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carton/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CartonNumber")] Carton carton)
        {
            if (ModelState.IsValid)
            {
                db.Cartons.Add(carton);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(carton);
        }

        // GET: Carton/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var carton = db.Cartons
                .Where(c => c.Id == id)
                .Select(c => new CartonViewModel()
                {
                    Id = c.Id,
                    CartonNumber = c.CartonNumber
                })
                .SingleOrDefault();
            if (carton == null)
            {
                return HttpNotFound();
            }
            return View(carton);
        }

        // POST: Carton/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CartonNumber")] CartonViewModel cartonViewModel)
        {
            if (ModelState.IsValid)
            {
                var carton = db.Cartons.Find(cartonViewModel.Id);
                carton.CartonNumber = cartonViewModel.CartonNumber;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cartonViewModel);
        }

        // GET: Carton/Delete/5
        // public ActionResult Delete(int? id)
        // {
        //     if (id == null)
        //     {
        //         return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //     }
        //     Carton carton = db.Cartons.Find(id);
        //     if (carton == null)
        //     {
        //         return HttpNotFound();
        //     }
        //     return View(carton);
        // }


       //Bug 1
        public ActionResult Delete(int? id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid carton ID.");
            }

            var carton = _context.Cartons.Include(c => c.CartonDetails)
                                        .FirstOrDefault(c => c.Id == id);

            if (carton == null)
            {
                return HttpNotFound("Carton not found.");
            }

            // Remove associated CartonDetails if any
            var cartonDetails = _context.CartonDetails.Where(cd => cd.CartonId == id).ToList();
            _context.CartonDetails.RemoveRange(cartonDetails);

            // Remove the carton itself
            _context.Cartons.Remove(carton);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        // POST: Carton/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Carton carton = db.Cartons.Find(id);
            db.Cartons.Remove(carton);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AddEquipment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var carton = db.Cartons
                .Where(c => c.Id == id)
                .Select(c => new CartonDetailsViewModel()
                {
                    CartonNumber = c.CartonNumber,
                    CartonId = c.Id
                })
                .SingleOrDefault();

            if (carton == null)
            {
                return HttpNotFound();
            }

            var equipment = db.Equipments
                .Where(e => !db.CartonDetails.Where(cd => cd.CartonId == id).Select(cd => cd.EquipmentId).Contains(e.Id) )
                .Select(e => new EquipmentViewModel()
                {
                    Id = e.Id,
                    ModelType = e.ModelType.TypeName,
                    SerialNumber = e.SerialNumber
                })
                .ToList();
            
            carton.Equipment = equipment;
            return View(carton);
        }

        // public ActionResult AddEquipmentToCarton([Bind(Include = "CartonId,EquipmentId")] AddEquipmentViewModel addEquipmentViewModel)
        // {
        //     if (ModelState.IsValid)
        //     {
        //         var carton = db.Cartons
        //             .Include(c => c.CartonDetails)
        //             .Where(c => c.Id == addEquipmentViewModel.CartonId)
        //             .SingleOrDefault();
        //         if (carton == null)
        //         {
        //             return HttpNotFound();
        //         }
        //         var equipment = db.Equipments
        //             .Where(e => e.Id == addEquipmentViewModel.EquipmentId)
        //             .SingleOrDefault();
        //         if (equipment == null)
        //         {
        //             return HttpNotFound();
        //         }
        //         var detail = new CartonDetail()
        //         {
        //             Carton = carton,
        //             Equipment = equipment
        //         };
        //         carton.CartonDetails.Add(detail);
        //         db.SaveChanges();
        //     }
        //     return RedirectToAction("AddEquipment", new { id = addEquipmentViewModel.CartonId });
        // }

        //Bug2

        public ActionResult AddEquipmentToCarton([Bind(Include = "CartonId,EquipmentId")] AddEquipmentViewModel addEquipmentViewModel)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the carton and equipment from the database
                var carton = db.Cartons
                    .Include(c => c.CartonDetails)
                    .Where(c => c.Id == addEquipmentViewModel.CartonId)
                    .SingleOrDefault();
                
                if (carton == null)
                {
                    return HttpNotFound();
                }

                var equipment = db.Equipments
                    .Where(e => e.Id == addEquipmentViewModel.EquipmentId)
                    .SingleOrDefault();
                
                if (equipment == null)
                {
                    return HttpNotFound();
                }

                // Check if the equipment is already assigned to the same carton
                var existingCartonDetail = db.CartonDetails
                    .Where(cd => cd.EquipmentId == addEquipmentViewModel.EquipmentId)
                    .SingleOrDefault();

                if (existingCartonDetail != null && existingCartonDetail.CartonId == addEquipmentViewModel.CartonId)
                {
                    // Equipment is already assigned to this carton
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Equipment is already assigned to this carton.");
                }

                // Check if the equipment is already assigned to another carton
                if (existingCartonDetail != null && existingCartonDetail.CartonId != addEquipmentViewModel.CartonId)
                {
                    // Equipment is already assigned to another carton
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Equipment is already assigned to another carton.");

CandidateProject/Views/Carton/AddEquipment.cshtml
@model CandidateProject.ViewModels.CartonDetailsViewModel

@{
    ViewBag.Title = "AddEquipment";
}

<h2>AddEquipment</h2>

<h3>@Html.DisplayFor(model => model.CartonNumber)</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Equipment.FirstOrDefault().ModelType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Equipment.FirstOrDefault().SerialNumber)
        </th>    
        <th></th>
    </tr>

    @foreach (var item in Model.Equipment)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ModelType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                @Html.ActionLink("Add", "AddEquipmentToCarton", new { cartonId = Model.CartonId, equipmentId = item.Id })
            </td>
        </tr>
    }

</table>

CandidateProject/Views/Carton/Create.cshtml
@model CandidateProject.EntityModels.Carton

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Carton</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CartonNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CartonNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CartonNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CandidateProject/Views/Carton/Delete.cshtml
@model CandidateProject.EntityModels.Carton

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Carton</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CartonNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CartonNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CandidateProject/Views/Carton/Details.cshtml
@model CandidateProject.ViewModels.CartonViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Carton</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CartonNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CartonNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CandidateProject/Views/Carton/Edit.cshtml
@model CandidateProject.ViewModels.CartonViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Carton</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CartonNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CartonNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CartonNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CandidateProject/Views/Carton/Index.cshtml
@model IEnumerable<CandidateProject.ViewModels.CartonViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CartonNumber)
        </th>
        <th>
            Number of Equipment
        </th>
        <th>
            Actions
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CartonNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EquipmentCount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
            @Html.ActionLink("AddEquipment", "AddEquipment", new { id = item.Id }) |
            @Html.ActionLink("ViewCartonEquipment", "ViewCartonEquipment", new { id=item.Id })
            
            @using (Html.BeginForm("RemoveAllItemsFromCarton", "Carton", FormMethod.Post))
                {
                     @Html.AntiForgeryToken()
                     @Html.Hidden("id", item.Id)
                     <button type="submit" class="btn btn-danger">Remove All Items</button>
                }
        </td>
    </tr>
}

</table>

CandidateProject/Views/Carton/ViewCartonEquipment.cshtml
@model CandidateProject.ViewModels.CartonDetailsViewModel

@{
    ViewBag.Title = "View Carton Equipment";
}

<h2>View Carton Equipment</h2>

<h3>@Html.DisplayFor(model => model.CartonNumber)</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Equipment.FirstOrDefault().ModelType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Equipment.FirstOrDefault().SerialNumber)
        </th>
        <th>
        </th>        
    </tr>

    @foreach (var item in Model.Equipment)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ModelType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                @Html.ActionLink("Remove", "RemoveEquipmentOnCarton", new { cartonId = Model.CartonId, equipmentId = item.Id })
            </td>
        </tr>
    }

</table>